### ISSUE TITLE
how to live longer with hair?

### ISSUE THREAD

**Issue by nkiki** [geekan/HowToLiveLonger#10]
any idea?

**Comment by Whyjsee** [comment]
less coding

**Comment by Whyjsee** [comment]
> any idea?

less coding

**Comment by zgbkdlm** [comment]
> > any idea?
> 
> less coding

no coding.

**Comment by XJL0930** [comment]
hhhhhfunny.Since be a programmer,don't think about it(bushi

**Comment by myd7349** [comment]
How to live with longer hair?

**Comment by OY9R** [comment]
I think baldness just a sign of sub-health. There is no direct relationship between baldness and coding.

**Comment by rinstartoooo** [comment]
Finasteride

**Comment by BodyCSoulN** [comment]
> 

Does this really help?

**Comment by hushyangqing** [comment]
Hair transplant?

**Comment by Unicorn-V** [comment]
Why not let hair free?

**Comment by dominikusbrian** [comment]
Use hair serum. water your hair, shine enough sunlight.

**Comment by haiker2011** [comment]
Use ADOLPH ! 😂

**Comment by MaitreChen** [comment]
coding happily😂

**Comment by 9a-aaaaaaaa** [comment]
no hair called big man!

**Comment by xuerzong** [comment]
404
