### ISSUE TITLE
引用链接的可信度思考

### ISSUE THREAD

**Issue by Michael18811380328** [geekan/HowToLiveLonger#12]
看到 readme 中某些链接，点开后发现是第三方的博客短文，这类文章是否有说服力？
例如：https://www.jianshu.com/p/5461a205cf95?utm_campaign=hugo
这个就是简书的一篇文章，可信度多高呢？

**Comment by Michael18811380328** [comment]
例如这种：“科普 | 喝咖啡又多了一个新理由：降低死亡率！”
https://www.sohu.com/a/439412995_100003595 
这种原文也不是非专业作者，值得思考
希望可以多引用一些权威机构的文档（至少是丁香医生这种公众号）

**Comment by AlbertZyc** [comment]
> 例如这种：“科普 | 喝咖啡又多了一个新理由：降低死亡率！” https://www.sohu.com/a/439412995_100003595 这种原文也不是非专业作者，值得思考 希望可以多引用一些权威机构的文档（至少是丁香医生这种公众号）

至少的丁香医生也不能作为参考，好歹也应该之高分期刊上的文章和数据

**Comment by geekan** [comment]
之前其他处的回复
> 我基本读过里面每一篇论文，即使以我的理解能力，我也认为理解起来也都比较困难（专业术语过多了），而且对于阅读体验也有很大的影响。而且，既然可以溯源，为什么认为不是官方的就没法李菊福？是觉得这些文章的解读不专业吗？那……谁能够有这么大的专业跨度做到每个领域都专业？如果你们觉得有一个比较好的方法能够两者兼得，也很欢迎来做贡献者。

**Comment by Navi-1993** [comment]
确实，有些引用看着就很反智。

**Comment by atxkm** [comment]
对，生活习惯对健康的影响是很大，若是保持了错误的习惯，还不如随心所欲可能对身体更健康。
如何保证参考的可靠性甚至真实性，比养成这种习惯本身更为重要，毕竟商业驱动的社会会有各种未知的动机。
如果不能保证信息的绝对正确，那跟听养生大师们的说教，没有什么分别。

**Comment by luchaoshuai** [comment]
中国5000年的文明，和西方500年的文明，不能就“论文”做决断。

**Comment by Michael18811380328** [comment]
> 如果不能保证信息的绝对正确，那跟听养生大师们的说教，没有什么分别。

我个人观点，上面短文中，喝咖啡和喝茶会降低死亡率，这个结论值得商榷。现在自媒体众多，很多水文都是商业洗脑文（例如喝红酒有利身体健康，适量的酒精有利身体健康等等，乙醇是世界公认的一级致癌物），所以需要个人判断。

**Comment by CoderViking** [comment]
这些链接得出的结论怎么保证是客观真实的，确实值得讨论。
比如我看到喝咖啡能长寿我的第一反应就是，这不是来推销咖啡产品的吧？
大家可以多找找权威的客观的案例，最好是能与国人文化传统与饮食生活习惯相匹配的

**Comment by maxiloEmmmm** [comment]
你还是换个思路去考虑比较好 说个比较寻常的例子

你google一个技术问题 得到了很多答案
最终筛选了正确答案
你为什么就可以断定这种google的结果可信度很高？
还不是你自己去测试及总结得到的答案？
难道你指望这个repo手把手喂你？
你要是有更好的答案你可以贴在issue 论文也好 博客也好 各种途径都行 大家一起讨论. 
你这issue算是啥 能有啥对于repo本身的推进？

**Comment by Michael18811380328** [comment]
> 你还是换个思路去考虑比较好 说个比较寻常的例子
> 
> 你google一个技术问题 得到了很多答案 最终筛选了正确答案 你为什么就可以断定这种google的结果可信度很高？ 还不是你自己去测试及总结得到的答案？ 难道你指望这个repo手把手喂你？ 你要是有更好的答案你可以贴在issue 论文也好 博客也好 各种途径都行 大家一起讨论. 你这issue算是啥 能有啥对于repo本身的推进？

我希望去掉一些不合适的链接，以免造成误导。你这是不是杠精？

**Comment by maxiloEmmmm** [comment]
> > 你还是换个思路去考虑比较好 说个比较寻常的例子
> > 你google一个技术问题 得到了很多答案 最终筛选了正确答案 你为什么就可以断定这种google的结果可信度很高？ 还不是你自己去测试及总结得到的答案？ 难道你指望这个repo手把手喂你？ 你要是有更好的答案你可以贴在issue 论文也好 博客也好 各种途径都行 大家一起讨论. 你这issue算是啥 能有啥对于repo本身的推进？
> 
> 我希望去掉一些不合适的链接，以免造成误导。你这是不是杠精？

你说不合适就不合适啊？ 你能不能用脑子读一读我说的 你有好的你拿出来啊 不识字么？二极管是不是
