### ISSUE TITLE
祖传手艺能否延长寿命？

### ISSUE THREAD

**Issue by Fancilan** [geekan/HowToLiveLonger#120]

**Comment by lyslol** [comment]
让女朋友帮你啊

**Comment by lauwen** [comment]
你不会没有女朋友吧

**Comment by lyslol** [comment]
new 一个对象啊，还可以自己定义

**Comment by zhangsanbin** [comment]
> new 一个对象啊，还可以自己定义

    class Boyfriend(object) :

    def __init__(self, tall, rich, handsome, love):
        if(tall >= 180):
            self.isTall = True
        else:
            self.isTall = False
        if(rich >= 100):
            self.isRich = True
        else:
            self.isRich = False
        self.handsome = handsome
        self.love = love

    def sayLove(self):
        if (self.love == True):
            print('I love you')
        else:
            print('Sorry')

    bf = Boyfriend(200, 200, True, True)
    bf.sayLove()

是这样吗？

**Comment by qhy040404** [comment]
> > new 一个对象啊，还可以自己定义
> 
> ```
> class Boyfriend(object) :
> 
> def __init__(self, tall, rich, handsome, love):
>     if(tall >= 180):
>         self.isTall = True
>     else:
>         self.isTall = False
>     if(rich >= 100):
>         self.isRich = True
>     else:
>         self.isRich = False
>     self.handsome = handsome
>     self.love = love
> 
> def sayLove(self):
>     if (self.love == True):
>         print('I love you')
>     else:
>         print('Sorry')
> 
> bf = Boyfriend(200, 200, True, True)
> bf.sayLove()
> ```
> 
> 是这样吗？

```python
def makeLove(self):
    if (self.love = love)"
        print('A baby is born')
    else:
        print('Nothing happened')

bf.makeLove()
```
狗头:dog:保命

**Comment by deepdarkfans** [comment]
> > new 一个对象啊，还可以自己定义
> 
> ```
> class Boyfriend(object) :
> 
> def __init__(self, tall, rich, handsome, love):
>     if(tall >= 180):
>         self.isTall = True
>     else:
>         self.isTall = False
>     if(rich >= 100):
>         self.isRich = True
>     else:
>         self.isRich = False
>     self.handsome = handsome
>     self.love = love
> 
> def sayLove(self):
>     if (self.love == True):
>         print('I love you')
>     else:
>         print('Sorry')
> 
> bf = Boyfriend(200, 200, True, True)
> bf.sayLove()
> ```
> 
> 是这样吗？


帮你修改了一下
```
class Boyfriend(object) :

def __init__(self, tall, rich, face):
    if(tall >= 180):
        self.isTall = True
    else:
        self.isTall = False
    if(rich >= 100):
        self.isRich = True
    else:
        self.isRich = False
    if(face>7):
       self.handsome = True
    else:
        self.handsome = False
    if(self.handsome and self.isRich and  self.isTall):
        self.love = True
    else:
        self.love=False

def sayLove(self):
    if (self.love == True):
        print('I love you')
    else:
        print('Sorry')

bf = Boyfriend(200, 200, 7.5)
bf.sayLove()
```

**Comment by hx804722948** [comment]
会让你流失大量亚精胺
