### ISSUE TITLE
我想问下如何根治鼻窦炎

### ISSUE THREAD

**Issue by mycherish** [geekan/HowToLiveLonger#124]
😷

**Comment by chainofhonor** [comment]
也许 换个空气好的环境可以解决  或者家里安装全屋新风系统 做到负压 即 所有进入家里的空气都是通过这个新风系统进来的

**Comment by geekan** [comment]
减肥、洗鼻、割鼻息肉 @mycherish

**Comment by mycherish** [comment]
> 减肥、洗鼻、割鼻息肉 @mycherish

最近在锻炼了，提高抵抗力，之前在医院开过吸鼻子的东西，洗过一段时间，可能稍微好一点，是不是要一直洗才行，我停了很久了，对但是洗鼻子好不好没啥感觉了，可能严重了就得去做手术了
