### ISSUE TITLE
Can we have an English version for this?

### ISSUE THREAD

**Issue by pushpeshkarki** [geekan/HowToLiveLonger#125]

**Comment by Sanzo00** [comment]
May be you can translate it and submit a PR.

**Comment by Interstellar750** [comment]
Did you notice that the English version already exists in the README file?
It was added in [this  commit](https://github.com/geekan/HowToLiveLonger/commit/780959df80b06f1fbc79e9d4badae680c1536e72)

**Comment by pushpeshkarki** [comment]
Apologies and thanks for the help.
