### ISSUE TITLE
为什么喝咖啡有好处？

### ISSUE THREAD

**Issue by lykpass** [geekan/HowToLiveLonger#126]

**Comment by yingshirun** [comment]
感觉喝咖啡的那个也就看一乐~

**Comment by wn0112** [comment]
总比喝红糖水有好处吧

**Comment by kaili-yang** [comment]
说得应该是美式咖啡，不加糖奶的那种

**Comment by judeng** [comment]
经常喝咖啡的往往都是中产以上阶级，这个因果关系就像科学家拆掉螃蟹腿去论证螃蟹听力在腿上一样~~

**Comment by hx804722948** [comment]
卖咖啡赞助的

**Comment by geekan** [comment]
@hx804722948 @judeng 并不是的。咖啡在欧美很便宜。
@lykpass @yingshirun 因果分析确实尚不完善，但是已经有极大规模研究可以做meta分析了，并且统计确实非常显著（不管什么来源）
