### ISSUE TITLE
Is there an English fork version of this?

### ISSUE THREAD

**Issue by moisestohias** [geekan/HowToLiveLonger#132]
Is there an English fork version of this?

**Comment by eamon2003** [comment]
![image](https://user-images.githubusercontent.com/51506762/215461330-2ee5a5fb-959f-4889-be80-257cb1c0be7e.png)

**Comment by LingkKang** [comment]
@moisestohias https://github.com/geekan/HowToLiveLonger/blob/main/README_en.md

👀
