### ISSUE TITLE
辣椒降低死亡风险那部分似乎可以完善一下

### ISSUE THREAD

**Issue by Rachel0x0** [geekan/HowToLiveLonger#137]
辣椒素可以降低死亡风险，但是我国的饮食习惯，吃辣的同时有可能会伴随着重油重盐的情况。而且对于胃部有疾病的人，吃辣会造成病情的加剧。

**Comment by ethanjtch** [comment]
那我们是不是可以点不辣的菜，后面单独加辣椒。比如，清汤火锅+辣味碟。

**Comment by Rachel0x0** [comment]
> 那我们是不是可以点不辣的菜，后面单独加辣椒。比如，清汤火锅+辣味碟。

我感觉这样要比辣油锅要好，我就是吃太多油腻的东西胆囊炎了。

**Comment by ethanjtch** [comment]
> 

去年开始，不知道什么原因，我平常都不怎么喜欢吃肉了，就是盯着青菜😂

基本上我的饮食就是，不喝奶茶不加糖，少吃红肉少吃辣。

**Comment by Rachel0x0** [comment]
> > 
> 
> 去年开始，不知道什么原因，我平常都不怎么喜欢吃肉了，就是盯着青菜😂
> 
> 基本上我的饮食就是，不喝奶茶不加糖，少吃红肉少吃辣。

可以定期去体检一下。我就是今年年初体检了，发现自己胆囊炎和甲状腺结节比较严重。现在就低油低碘饮食。

**Comment by ethanjtch** [comment]
OK

发件人: Rachel ***@***.***>
日期: 星期一, 2023年4月3日 17:51
收件人: geekan/HowToLiveLonger ***@***.***>
抄送: Ethan Chen ***@***.***>, Comment ***@***.***>
主题: Re: [geekan/HowToLiveLonger] 辣椒降低死亡风险那部分似乎可以完善一下 (Issue #137)

去年开始，不知道什么原因，我平常都不怎么喜欢吃肉了，就是盯着青菜😂

基本上我的饮食就是，不喝奶茶不加糖，少吃红肉少吃辣。

可以定期去体检一下。我就是今年年初体检了，发现自己胆囊炎和甲状腺结节比较严重。现在就低油低碘饮食。

**Comment by townechow** [comment]
吃辣可以降低死亡率的观点其实挺扯的

假设观察到现象：吃辣的人普遍长寿，或者长寿的人普遍吃辣；

那么是否可以得出结论： 吃辣有利于长寿；

显然是不可以的

因为可能存在情况，吃辣的人身体素质本来就比较[好]，生理机能能应对 [辣] 的刺激；而身体素质本来比较[差] 的人，生理机能无法应对[辣]的刺激；身体的生理反应使得不同的体质对于[辣]的反应不同， 前者趋之，后者避之；

如果本身就不适应吃辣的人，为了所谓的[吃辣长寿]而强行吃辣，可能会直接gg😑

**Comment by geekan** [comment]
@townechow 是的。你观察到了“统计显著”并非“因果”。大部分study是无法观测到直接因果的。
