### ISSUE TITLE
建了个微信群交流一下这方面的健康知识

### ISSUE THREAD

**Issue by guizhenwei** [geekan/HowToLiveLonger#139]
长期践行控糖，低碳水/生酮饮食，多户外，适量运动，改善睡眠，注意调节压力等生活方式，可以极大程度上预防和改善心脑血管系统方面的健康问题。

我建了一个相关的健康微信群，欢迎朋友们一起入群交流心得体会。

注：
因进群发广告的太多（都一一踢出了），现在改成添加微信，再拉入群内了。烦请添加以下微信号，备注：进健康群

![拯救世界的蝙蝠侠_微信二维码_20230531120906](https://github.com/geekan/HowToLiveLonger/assets/12146658/a0f09c0c-203b-414e-8d16-56f068be90ae)

**Comment by hanxiaomeme** [comment]
微信群过期了 能重发一个吗

**Comment by guizhenwei** [comment]
如果微信群二维码过期了，请加如下这个账号的微信，拉您入群交流。

![拯救世界的蝙蝠侠_微信二维码_20230531120906](https://github.com/geekan/HowToLiveLonger/assets/12146658/0d711d42-56db-43b5-94a9-539f386720ac)
