### ISSUE TITLE
建议增加代糖对死亡率的影响

### ISSUE THREAD

**Issue by CFSO6459** [geekan/HowToLiveLonger#146]
我目前已知的有害代替包括 赤藻糖醇（erythritol，注1）和 阿斯巴甜（aspartame），其他代糖也有可能致死，望查证，谢谢。

注1：
The artificial sweetener erythritol and cardiovascular event risk. Nature medicine 29 (3), 710-718, 2023
https://drive.google.com/file/d/0BwFc5q6qBeqbUE1ZRmJXc09Cc2c/view?usp=drivesdk&resourcekey=0-8HepaXWaiS_lIWcfjViJBg

**Comment by geekan** [comment]
搜索正文：无糖
