### ISSUE TITLE
不同时间段睡觉的效果应该是不一样的，几点开始睡比较好呢？

### ISSUE THREAD

**Issue by SDF001** [geekan/HowToLiveLonger#157]
比如同样是睡8小时，22:00～6:00和00:00～8:00应该是不一样的，中医里面有按照时辰来养生的说法，所以有没有这方面的研究比较明确的说明的每天几点睡觉几点起床会比较好呢？

**Comment by Stoneleee** [comment]
入睡时间建议22~24之间
