### ISSUE TITLE
为什么要强调程序员

### ISSUE THREAD

**Issue by Nomyfan** [geekan/HowToLiveLonger#18]

**Comment by geekan** [comment]
他处文本
> 最开始收集这些数据的原因也是早年听家里老人念叨各个养生方法，也经常听他们讲中药、土法、玄学，但我也不能反驳，且实际大部分都并不科学，所以萌生的年头：“要不做下量化计算？”
其实现在经常会听到 human-in-the-loop 的观念，很多时候把人当成了一个 object ，你看这个文档，只是修改了不同的输入、输出、上下文，就可以改变人。
