### ISSUE TITLE
酒，每周100g内，以多少酒精含量的酒为基准呢？

### ISSUE THREAD

**Issue by zion-c** [geekan/HowToLiveLonger#2]

**Comment by geekan** [comment]
之前算的是每周纯酒精100g内，但是不一定（算的）正确。看了一下确实没有把相关文档放上来
#TODO 证据-输入-液体-酒精

**Comment by XJL0930** [comment]
You are right.I think this is a serious question,especially for the people who love drinking like me.

**Comment by AlbertZyc** [comment]
> You are right.I think this is a serious question,especially for the people who love drinking like me.

You can refer to this article 《Risk thresholds for alcohol consumption: combined analysis ofindividual-participant data for 599912 current drinkers in 83 prospectivestudies》

**Comment by geekan** [comment]
https://github.com/geekan/HowToLiveLonger/pull/14

**Comment by youxingz** [comment]
为什么是100，不是128？我觉得要符合自然指数增长，不应该用十进制约化，这样可以多喝一点
