### ISSUE TITLE
关于复合维生素补剂

### ISSUE THREAD

**Issue by scarsu** [geekan/HowToLiveLonger#3]
> 刻意多补维生素C会导致泌尿系结石，甚至会出现一些血液疾病，所以合理饮食最重要。

![](https://scarsu.oss-cn-shanghai.aliyuncs.com/picgo/20220418104812.png)

**Comment by geekan** [comment]
nod. 非常同意。如果可以，你可以尝试修改文档，这个文档还有不少可以优化点
维生素这块我特意写了除了8%的额外防癌作用其他无用。
