### ISSUE TITLE
多吃辣是这里理解不到，会不会是能吃辣而不是多吃辣

### ISSUE THREAD

**Issue by BOMBOMBANG** [geekan/HowToLiveLonger#31]

**Comment by wyrover** [comment]
多吃辣（辛）味食品，会伤肝，肝火会更旺，如果年轻时已经熬夜过度，或者脂肪肝，不要吃辛辣食物。不然导致肝肾阴虚，阴阳失调，肝阳上亢，直接后果就是高血压，更不要提什么保护心血管。
