### ISSUE TITLE
吃蛋黄分人的吧

### ISSUE THREAD

**Issue by rodericklgp** [geekan/HowToLiveLonger#36]
蛋黄也是鸡蛋中的一部分营养物质，鸡蛋中主要的矿物质、维生素、磷脂等在蛋黄中。蛋黄的主要成分是17.5%的蛋白质，32.5%的脂肪，还有大约48%的水和2%的矿物质，以及多种维生素等。蛋黄富含脂溶性维生素,单不饱和脂肪酸，磷，铁等微量元素。
蛋黄中有宝贵的维生素A和维生素D，还有维生素E和维生素K，这些都是“脂溶性维生素”。水溶性的维生素B族，也绝大多数存在于蛋黄之中

**Comment by HGladiator** [comment]
蛋黄这里有一些研究看着不影响啊， https://www.zhihu.com/question/24309336

**Comment by geekan** [comment]
影响。胆固醇太高了。如果有其他研究可以拿出来对比

**Comment by district10** [comment]
蛋黄中胆固醇含量和（人吃了之后）血液中胆固醇含量没什么关系。
