### ISSUE TITLE
为啥吃水果降低风险，喝果汁却增加风险？

### ISSUE THREAD

**Issue by ganchu** [geekan/HowToLiveLonger#37]

**Comment by caimengnan** [comment]
果汁需要各种添加剂维持新鲜和口感，水果纯天然

**Comment by ray-008** [comment]
和量有关吧？一杯果汁要的水果量多了，吸收的糖分就上去了。糖又是增加风险的。[旺柴]

**Comment by LadyForest** [comment]
看你怎么定义果汁了, 大部分超市开架果汁都添加了蔗糖 (这算比较良心的), 有些还会加果葡糖浆, 这玩意儿简直是热量炸弹.
如果是原榨还会好一些, 但是它相比水果更好消化, 所以相同饱腹感的情况下, 果汁摄入比水果量会更多, 热量就上去了. 另外水果也不是越多越好, 果糖和葡萄糖的代谢不太一样, 我如果没记错的话果糖代谢需要借助肝脏, 所以西瓜等糖分高的水果也要少吃...

**Comment by zhangkaizhao** [comment]
搜索“水果 果汁 果胶”可以得到很多有用的资料，比如这一篇：
“吃水果”与“喝水果”的利弊分析 https://www.caas.cn/zt/swyyzlyaq/zjsd/259747.html

**Comment by CcWeapon** [comment]
果汁打碎 吸收的更快？

**Comment by deerLoves** [comment]
现在水果含糖量太高，往往是一杯果汁需要多个水果来进行榨取，含糖量直接就上去了，打碎喝比较健康。

**Comment by geekan** [comment]
是的。单颗水果吸收较慢，含糖较低，提供饱腹感与纤维素。果汁这些都没有

**Comment by LadyForest** [comment]
> 果汁打碎 吸收的更快？

吸收快不快不知道, 但是应该升糖更快...
