### ISSUE TITLE
WhyLiveLonger?

### ISSUE THREAD

**Issue by Jingkang50** [geekan/HowToLiveLonger#39]

**Comment by geekan** [comment]
https://book.jd.com/writer/Search?keyword=%E5%93%B2%E5%AD%A6%E7%B1%BB%E4%B9%A6%E7%B1%8D&enc=utf-8&spm=2.1.12

**Comment by lvyandev** [comment]
HowToDiePainlessly

**Comment by atidat** [comment]
> https://book.jd.com/writer/Search?keyword=%E5%93%B2%E5%AD%A6%E7%B1%BB%E4%B9%A6%E7%B1%8D&enc=utf-8&spm=2.1.12

funny

> https://book.jd.com/writer/Search?keyword=%E5%93%B2%E5%AD%A6%E7%B1%BB%E4%B9%A6%E7%B1%8D&enc=utf-8&spm=2.1.12

funny

**Comment by atidat** [comment]
> https://book.jd.com/writer/Search?keyword=%E5%93%B2%E5%AD%A6%E7%B1%BB%E4%B9%A6%E7%B1%8D&enc=utf-8&spm=2.1.12

funny

**Comment by atidat** [comment]
> HowToDiePainlessly

How 2 Live Peacefully

**Comment by wn0112** [comment]
只要我们不努力，他们就过不上想要的生活
