### ISSUE TITLE
睡眠应该降低全因死亡率

### ISSUE THREAD

**Issue by JaneLong** [geekan/HowToLiveLonger#4]
早睡+43% ACM，晚睡+15% ACM,所用到符号应该是-的

**Comment by gaochengyidlmu** [comment]
看上去是说要在 10-12 点间睡觉，早了晚了都不好

**Comment by geekan** [comment]
@gaochengyidlmu 对的。
@JaneLong 如果觉得这个写法有歧义，可以直接contribute一个更好的写法

**Comment by imhjnju** [comment]
关于这个时间，10-12点，如果真的从人的自然节律来讲，应该是当地自然时间，这个会跟经度有关，但是作为社会节律来讲，国内用的都是北京时间（120° E），如果同一时间睡的话，这一点，就成都（102°E左右）来言，都差了1个小时了。当然10-12点是一个范围内，不过单单就考虑社会节律跟自然节律的错配，似乎，还是按照每个人感知调整的好。
