### ISSUE TITLE
加班、运维半夜被叫醒的相关性统计

### ISSUE THREAD

**Issue by lvwangbeta** [geekan/HowToLiveLonger#41]
建议增加这些跟工作性质相关的活动对寿命的影响因素

**Comment by wyrover** [comment]
这些工作没办法，如果长期被叫醒，要辞掉工作，最好让运维全部自动化报警，提前做好演练。

**Comment by geekan** [comment]
解看起来是solid cloud native infra

**Comment by Kanayukii** [comment]
倒是可以增加 “加班对ACM的影响” 以及 “半夜/不规律的被叫醒 对ACM的影响”
咱记得长期不规律的被叫醒会导致心脏疾病（
