### ISSUE TITLE
老中医给的 100 条养生建议

### ISSUE THREAD

**Issue by wyrover** [geekan/HowToLiveLonger#42]
中医养生，就是指通过各种方法颐养生命、增强体质、预防疾病，从而达到延年益寿的一种方法。中医养生的目的是提前预防疾病，治未病。

以下这中医养生 100 条，养生防病一定要记牢！

1. 记住：睡觉是养生第一要素。

睡觉的时间应该是晚 21：00~ 早 3：00。因为这个时间是一天的 “冬季”，冬季主藏，冬季不藏，春夏不长，即第 2 天没精神。

2. 一切药物对治病来说都是治标，不是治本，不管是中医还是西医。

因为一切的病都是错误的因产生错误的果，错误的因不除，错误的果就不会绝根。健康的根本在心，一切法从心生，心净则身净。所以得病了，不要向外求，要靠自己自身的修复系统来修复自己的疾病。其实人和动物是一样的，动物的病都是靠自己，人也能。

3. 正确的观念，远比昂贵的药物和危险的手术更能帮助患者消除疾病。

有了正确的观念，你就会有正确的决定，你就会有正确的行为，你就可以预防许多疾病的发生。

4. 人所具有的一切智慧，绝对不是从书本里学来的，而是从自己的真诚心、清净心 (就是佛家所说的菩提心)，从定中生出来的。

5. 人是一切生物中构造最完美的灵体，健康的身体是人生来就具足的。

人的健康状况的调节是靠人体本身所具有的调节修复系统来完成的，而不是靠外部因素，外部因素只能起辅助作用。

6. 人的大部分生病现象是人体在调节、清理身体垃圾时所表现的现象，是人体自动调节平衡所表现出的状态。

所以应该把它们当成正常的生理现象，而不应该去把它当成病因来消灭。所以当人在生病的时候，一定不要有怨恨嗔恚心，心里要安定，心定则气顺，气顺则血畅，气顺血畅则百病消。

7. 人的健康离不开两大要素：

（1）足够的气血；

（2）畅通的经络 (包括血管和排泄垃圾的通道)。

8. 足够的气血靠：

足够的食物 + 胆汁 + 必要时间内 (晚天黑后～午夜 1 点 40) 优质的睡眠 (这个时候大脑完全不工作，由植物神经主导)+ 良好的生活习惯。

9. 畅通的经络需要：

清净心。一切七情六欲都会破坏清净心，从而破坏经络的正常运行。

10. 维持健康的身体不仅需要 “增收 (增加气血)”，也需要 “节支 (减少血气的损耗)”。

11. 过度地增加食物不仅不会增加血气，而且会成为身体中的垃圾负担，反过来还得靠消耗血气来把他们清理掉。

五脏六腑是一个血气加工厂，食物是原材料，加工能力是有限的，而食物是无限的，所以食物的数量必须得到控制。

12. 适当运动可以帮助人的气血运行，但同时也在消耗人的气血。

人体的微循环主要应该靠松静来达到的，这也是健康必不可少的。

13. 人体中的垃圾越多，就越需要更多的血气来清除它们，但人的血气因为垃圾的增多和血脉的阻塞而减少，这就形成了恶性循环，这也正是人衰老的机理。

所以，人要想健康不老，就要：

（1）减少体内的垃圾；

（2）增加血脉经络的畅通；

（3）增加体内的气血。

14. 与其相信药物，相信检查的数据，不如相信自己的感觉，相信自己所具足的自我调节能力。

但这需要在你得道 (智慧开了) 的前提之下，才能分辨这一切。

15. 健康，从调节心性开始。

16. 对于一个有宿疾的人来说，只有气血充足了 (一是通过这里所介绍的补充气血的方法，二是通过静坐打通气)，病情才会显现出来。

这个时候要沉住气，定下心来多做些静功来增加自己的气血，以尽快度过这个时期。

17. 人违背了养生法则，虽不一定会立即得病，但一旦形成习惯，就会大大增加得病的机会。

这就和交通规则一样，你违背了交通规则，不一定会出事故，但其危险性是显而易见的。

18. 人为什么必须保持一定的饥渴才是对养生有利呢？其实这就是 “虚” 的妙用。

道家讲，虚则灵。这和谦虚使人进步，自满使人落后一样，所以人必须经常保持 “虚灵” 的状态，才能时时保持清醒，保持健康。

19. 人要想健康，就必须使体内有足够的 "气" 来 "气化" 所进的食物。

只有这样，你的体内才不会积累垃圾，不会有多余的食物来释放游离的 "虚火" 损害你体内的脏器。这个 "虚火" 反过来会损耗你的 "气"。所以，从这个意义上来讲，现代人生病，大多数是饮食不节的缘故。

20. 甜言夺志，甜食坏齿。

21. 俗语说 “灵机一动，计上心来”。

这个 “机” 字如果能真正领悟透了，那么你的悟性就算是开了。老师教人，医生治病，其实就是在点拨你的这个 “机”，让你 “机” 打开。这个 “机”，有时也叫 “关键”。当然，这个 “机” 起作用是有条件的，就和氢气只有达到一定浓度，遇火才可以燃烧爆炸一样。记住，别人的作用都是外因，你自己才是真正的内因。

23. 人生最忌是个乱字，心乱了，对外可以紊事，对内可以打扰血气，使失正常。

凡恼怒恐怖喜忧昏疑，都是乱，为多病短寿的根源，不但养病时不应乱，即平居时亦忌心乱。

24. 多嗔伤肝，多淫伤肾，多食又伤脾胃。忧思伤脾，愤怒伤肝，劳虑伤神。

25. 身病之起，无不由心虚弱，外邪乘入。

而心虚气弱，每由心魂恼乱，真体不充，发现种种不安。贪食、贪胜、贪得、贪乐逸，皆足以致病。以贪之不得，于是乎嗔。贪嗔可使心荡气促，胆惊肝旺，六脉震动，五脏沸腾，外邪同时乘入，此病之起因。

26. 凡人欲求长寿，应先除病。

欲求除病，当明用气。欲明用气，当先养性。养性之法，当先调心。

27. 人受五行之气而治生，故肉身以气为主。

气亏则病，气滞则病。欲治其病，先治其气。

28. 气以行血，血以补气，二而一也。

凡人久视则伤血、久卧伤气、久坐伤肉、久立伤骨、久行伤筋，七情六欲之过则伤元气、伤心肾。相火旺，真阳耗，

29. 治五脏之病，莫先于补气。

肾犹亟焉。补气在勿动心，心动则肝旺，各脉震惊，真水耗损。心为扇，主引风。风动则火旺，火旺则水干，水干则地损。

30. 心定神一，受治者信坚心专，两心相合，可以统治百病，无不神效。

31. 人病可分两种：

一是经络基本畅通但气不足。表现是经常这疼那疼，这是因为他气不足以气化食物，而产生了相火 (也叫虚火)，随着经络在体内乱穿，哪儿通走哪儿，遇到一个地方堵塞了，这个地方就疼了。这样的人吃一点药物就会立即见效。

二是经络不通，气也就无处存身。表现在外表看不出有什么毛病，但一旦发现就是大病，而且这种人经常是吃什么药都见效慢，或根本不起作用。

32. 中医的最高境界是养生，养生的最高境界是养心。

所以，就养生而言，下士养身，中士养气，上士养心。看一个人也是一样，观相不如观气，观气不如观心。

33. 心神不安，情性燥急，为致病致死之总因。

故安心法，为卫生第一要诀。心可以主动一切。心定则气和，气和则血顺，血顺则精足而神旺，精足神旺者，内部抵抗力强，病自除矣。故治病当以摄心为主。

34. 风寒阴阳暑湿，在在皆可使人致病。

万一抵抗力薄弱，即可乘虚而入。身弱者多病，即是此理。富人有保卫力，如衣食住等等。贫人有抵抗力，如气足神旺，毛孔厚密，不易侵入等等。富人多食肥甘，伤胃伤齿。贫人多饿，所食不杂，故无肠病。

富人多逸，故多气恼。贫人多劳，故少疾病。富人不造福而享福，只是消福，消尽则穷。穷人能勤俭，即是造福，果熟即富。凡衣食住之保卫力富，则精气神之抵抗力弱。保卫力弱，则抵抗力强。

35. 大病初愈，切忌理发、洗足、沐浴。

36. 故求长寿无病，常强肉身。

欲强肉身，当调伏精气神。欲调精气神，当拒绝扰乱之贼。欲杜此贼，当先摄心。欲求摄心，当化贪嗔痴三毒。欲化除此三毒，必学心戒。但空口言戒，无益于事，必求开慧，方不为所愚。欲求开慧，必先求定。欲求得定，必学静坐。

37. 能静则仁，有仁则寿，有寿是真幸福。

38. 一切修身修心法门，只有两字诀：

曰放下、曰回头。放下屠刀，立地成佛；苦海无边，回头是岸。只要一放下，一回头，病者顿愈，迷者顿觉。此真无量寿者。

39. 心过劳的人，心疲肝旺，心过劳就是心太满，不虚。

心满，则不纳肝 (木) 生之火，心不纳肝生之火，则肝气必积而盛。肝木克土，脾胃受病，消化不良，营养不足，夜眠不安。土又克水，于是肾水大亏，水不足则火更旺，心肾相联，心气更弱，肺病即成。

内部相互关联，一动全动，一病全病。而扰之者，乃在妄心，所以治病在安其心，安心在息妄，息妄在明心，明心即自觉，而健康的功效在乎静坐。

40. 静坐是息心法，心息则神安，神安则气足，气足则血旺，血气流畅，则有病可以去病，不足可以补充，已足可以增长。

现在病可去，未来病可防，此其小者也。又心息则神明，神明则机灵，静者心多妙，观机辨证，格外敏捷，见理既正，料事益远，遇乱不惊，见境不惑，能一切通达，自无主观偏执之弊，而大机大用，由此开启矣。

41. 人在生病的时候最忌讳是嗔恚心起。

这个时候一定要安然顺受，让心安定。然后慢慢调理，健康很快恢复。心安才能气顺，气顺才能除病。否则心急火上，肝气受损，加重病情。心神宁一，那浑身的血气，自可健全发挥。

心有两种，一是真心，一是妄心。真心是水，妄心是波，波因风动，风止波息，而水不动。寂然无念，是无心心也。

42. 子时失眠，肾水必亏，心肾相连，水亏则火旺，最易伤神。

43. 睡时如有思想，不能安着，切勿在枕上转侧思虑，此最耗神。

44. 午时属心，此时可静坐一刻钟，闭目养神，则心气强。

45. 早起如在寅时三点至五点，此时切忌郁怒，不然必损肺伤肝，万望注意。

46. 人生一切事业，皆以精神为根本。

而精神之衰旺强弱，全赖心神之静定不乱，一个乱字，足以妨碍一切工作。

47. 人生以血气流通为主，气滞可以阻血，血阻可以结毒为疖为瘰，为癌为瘤，皆是血气不流通之故。

气以顺为主，血以通为畅。百病无不先由气滞，气郁于内，肝先受伤。挽救之法，在化除得诀。而化除要诀有二：第一寻其根，其根在心，心空则一切自化。第二以药石、按摩助其化除，帮助血气之流通。

48. 养病治病不可求速。

因性急助火，火旺损气，反而不美。另不可贪多，贪则无恒而性急，况百病由贪而起，不可再贪以重增病苦也。

49. 心属火、肾属水，心肾相连。

火宜降下，水宜上升，水火相济，则蒸气内发。各部机体运动，可求得健康。此可于舌上察知。舌无水则不活，故活字以三点水加舌字。舌上可以报告内部各种病状深浅，以断生死。

50. 欲得养生，肠中常清。

51. 静养法：

安坐 (卧) 在床上，把身心一齐放下，自己浑身如融化，不许用一毫气力，好像没有这个身子相似。呼吸顺其自然，心也不许它用一点力，一起念便是用力了。把心安在脚底板下，此是引火向下，引水向上，自然全身气血顺畅。

52. 修行要诀：寂照照寂，切忌用力成佛作祖无他秘密。

具体要求：不许任何部分用一点气力，包括意念、呼吸、肢体，做到：眼不观，耳不闻，鼻不嗅，舌不尝，口不纳，心不想。此是唯一条件。若有所思所闻所觉，即是用气力，甚至乎使臂指即是用气力。呼吸稍粗亦即是用气力。

不久那呼吸自然而平，似乎不由口鼻内出纳，而浑身八万四千毛孔中有了动作，或张或翕，此时无我无身无气无心，天然心归本位。所谓引火归元，又名水火既济，为治疗百病之总诀。

53. 为了养生而死的，占十分之三。

到底怎么回事？是因为太爱惜自己的身体了。为了这副臭皮囊，怕受辱，怕受宠，怕吃亏，怕上当，瞻前顾后，左顾右盼，担惊受怕，患得患失・・・・・・这样，他那颗心整天缩成核桃样，像是被狗反复啃过，怎么能不死。

越怕死，越死得快。你要是养生，就得不怕死。只有不怕死，才能远离死。真正不怕死的人，走路不会遇上老虎，就是遇上老虎也不吃他。打仗遇不上刀枪，就是遇上，刀枪也不伤他。为什么？因为他不把死当回事，不怕死，死也就没法了。

养生，并不是修道的目的，但是修道的人已经看透了生死，所以不再怕死，既然已经不再怕死，那么死也就不再是问题。生死这一关过去，还有什么过不去的？因此，修道的人能够长生。没想到长生，反倒能长生。一心想着长生，反而死得快。长生不是修道的目的，它只是修道的附带现象。

54. 人有病，人还不以为有病，这就是人的最大的病。知道自己有病的人有多少呢？

55. 天天三更半夜还在网上的人，本身就是养生的大忌。

包括一些所谓的名医也是这样。还有，他们的心量也是斤斤计较，试问这样的人连自己都保不住，还怎么医人呢？

56. 别贪那个小便宜，大便宜也别贪。

一个贪字就含着祸。贪，患得患失会导致人得心脏病。贪，患得患失是不懂道法自然的表现。

57. 不要天天想着吃什么补阴，吃什么壮阳。

记住了，运动就可以生阳；静坐就可以生阴。阴为阳之母，阳为阴之用。

58. 人在气不足的时候，不能盲目补气，否则会影响身体健康。

如果是因为血不足，就需要先补血，因为血为气之母，否则就成了干烧器皿，把内脏烧坏；如果是因为淤滞不通，就可以增加气血，血气同补。这样才能达到补气的作用。

59. 环境对人养生的重要性是不言而喻的。

这就是为什么人在空气清新的深山老林里，会把痼疾养好的道理。因为深山老林中的精微物质 (负离子) 会通过人在放松情况下的深呼吸把它吸收到人体内部，从而滋润孕养五脏六腑，使人重新焕发活力。

还有重要的一点常人并不所知，就是人不仅仅是通过口鼻来呼吸，人身体的每个汗毛孔都是可以呼吸的，而且正是它们吸取着天地的精华。

60. 人在松静的状态下，慢慢深呼吸就能体会到人和天地精微之气的交换：

在吸气时，实际除了肺在吸气，整个身体是在把体内的气向外排，即把人的气释放到天地；而肺在呼气时，实际人是在通过全身毛孔吸收天地的精微之气。这大概就是老子所说的 “天地之间，其犹橐龠乎”。

61. 运动有两点禁忌：

（1）不能在气血不足的时候运动；

（2）不能在污浊的环境中运动。

62. 运动的作用有二：

（1）是增加气血的运行速度，促进体内的垃圾排出体外；

（2）是打开皮肤的毛孔，吸收天地精气。

63. 什么是悟性？什么是智慧？悟性和智慧就是用最简单的方法来处理、看待一切事物。

但一些庸人自扰的人总是把简单的事情看复杂了、做复杂了。繁和简其实是一回事，是一回事的两个方面。聪明的人看到的是简单的一面，愚蠢的人看到的是复杂的一面。

64. 饭前喝汤，胜过药方。

65. 戒烟限酒，健康长久。

66. 热水洗脚，如吃补药。

67. 根据阴阳互抱的原理来看，清与浊相互吸引。

所以人食入清新之物必将与体内污浊之物相抱，从而把它们排除体外。

68. 污浊之物的产生一是因为食入不干净食物，但更主要的是食入了过多的食物，体内不能运化造成食物堆积成垃圾。

69. 顺应自然是养生的最高境界。

一个人生下来，他的命运就基本上是有一定定数的。他该干什么，不该干什么，该吃什么不该吃什么，如果能顺着他的运数去做，就会平安无事。有悟性的人会发现、知道自己的运数，知道他应该干什么，不应该干什么。

所以养生绝对不是简单模仿，人云亦云。不要去羡慕别人，要从自己的心里找到自己的悟性。那么人如何才能发现自己是否顺其自然了呢？其实这太简单不过了，你有病了，你不舒服了，你不自在了，那你就是违背自然了。要做到顺外面大自然的自然，还要顺自己内在命运的自然，这二者是不可或缺的。

70. 很多人一听到医师宣布自己得了重病时，往往都会显现出一副无辜的模样，希望用切、割、毒、杀等外来方式去除疾病，然而，疾病真的会没来由地产生吗？

世上绝对没有这种 “好好的就突然生病的事情”。以感冒为例，如果真要病人作自我反省的话，通常患者都会表示，自己在感冒之前，曾经一连熬了好几个通宵；有些人会说，自己最近吹了冷风、淋了雨；有些人则说，工作的压力很大，常常头痛又失眠。事实上，诸如此类现象，都是导致感冒的因素，接句话说，假使病人的敏感度及警觉性够的话，自然能够做到 “防患未然” 的目标。

71. 胡萝卜，小人参；经常吃，长精神。

72. 没有怕吃亏的心，没有占别人便宜的心。

换句话说，就是你能吃亏，别人就是要你命你都舍得，你都给他，而自己在任何时候都不去贪便宜，那你的心还能不定吗？世人谁能做到？但佛就做到了。

73. 人有童心，一世年轻。

74. 学问深时意气平，心定则气平。

所以对于一个得道的人来说，观察一个人，并不是一件很困难的事，这也是相随心转的结果。

75. 名为五欲之最难破者，色次之，财又次之，食与睡更次之。名心不死，无以入道。

76. 百病之始，起于风邪乘入。

如体气虚弱，营卫失调，或忧思惊恐，酒色劳力，真气耗而外邪入矣。

77. 治五脏之病，莫先于补气。

肾犹亟焉。补气在勿动心，心动则肝旺，各脉震惊，真水耗损。心为扇，主引风。风动则火旺，火旺则水干，水干则地损。

78. 对于医生而言，心定神一，受治者信坚心专，两心相合，可以统治百病，无不神效。

79. 对付一些顽固的病症，不能正面硬攻，要从其他的相关方面突破。

如治疗肾病，肝病这些顽固之症，可通过调肺、脾等来达到效果。

80. 中庸，是养生的根本原则。

人体中的气血也是一对阴阳，血为阴为体，气为阳为用。血为气之母，气为血之帅。气不足，易得淤积之病，如肿瘤、血栓等；气太过，易得脑出血之类的病。所以，只有气血平衡，人才能健康。

81. 人只有悟到什么是 “自然” 了，才算是得道了。

知道自然，然后能顺其自然，这个人就是神人。懂得阴阳了，懂得顺其自然了，你就一定会成为良医大德了。

82. 什么是自然，自然就是任何事物都有阴阳两面，任何事物都要经过生、长、收、藏的过程。

你顺应这个过程，采用五行相生相克的原理去调节病人的平衡，怎么会治不好病呢。

83. 简单和复杂是一对阴阳，越是复杂的事情，往往用最简单的办法就可以解决。

同样，看似最简单的问题，你往往解决起来并不容易，你付出极大的努力也不一定能解决得了。这就和刚柔一样，柔极能克刚，刚极柔不防。

所以，我们在解决问题的时候就要有这个思路，遇到复杂的问题要去找简单的方法解决，遇到简单的问题不要忽视它，要引起足够的重视。就和毛主席所说的那样，战略上藐视，战术上重视。就是对问题给予藐视，对过程引起重视。

84. 若要百病不生，常带饥饿三分。

85. 什么是平衡？平衡就是阴阳的互相依存和互相制约，哪一方太过或不及都会失去平衡。

怎么会伤元气，失去平衡就是在伤元气。经常处于平衡的状态，元气就会保持得好，人就衰老得慢。

86. 阴阳之道就是矛盾对立的两个方面互相依存、互相转化。任何一对矛盾，如果一方脱离了另一方，不受另一方的制约了，那它离消失、灭亡就不远了。

大自然中，一个事物的出现，总有令它产生的因素，但同时总会出现另一因素来制约它。这就是五行相生相克的道理，也是阴阳相互依存、相互制约的道理。所以养生的道理也是如此，你生病了，总有一个使你生病的因素存在，同时也会有一个制约它，令你疾病消失的因素存在。正如自然界中毒蛇存在的地方，必定附近就有解蛇毒的草药存在一样。

87.  吃米带点糠，营养又健康。

88. 如何具有大智慧？没有博大的胸怀，哪来的大智慧。

89. 俗语说，活到老，学到老。

学习也要应时，到什么年龄就要学他这个阶段应该学的东西，否则就是不应时，不顺其自然。但看看我们现在的教育，从幼儿园到大学，有多少是学了应该学的东西。

小时候应该学什么，应该学德，学孝道，接着学识字断句，再往下学如何做事。到青年学如何优生优育、家庭幸福。到了中年，学习养生之道。到了老年，学放下心态，安享晚年。继续教育学什么，就是要学这些。

90. 五志能够致病，五志亦能解病。

情志跟疾病的相关性是很密切的，有些疾病就是因情志而起，你用药物治疗，治来治去都不好，对于这类疾病，解铃还需系铃人。

91. 养生有一条很重要，就是不能怕死。

怕死者阳气不足，阳气不足，死神就会找到你。这就是道家所讲的，修炼人要有英雄的气质。仁、智、勇三者缺一不可。

92. 当你把什么学问理解到它是非常简单朴素的时候，这时候你才是真正得到其中的三昧了。

如果你还感到它是那么博大精深，深不可测，那是你还没有掌握到它的精髓，是只见到茂密的树叶，而没看到根本，这时候你还是处于 “有” 的阶段，没有达到 “无” 的境界。一切离不开阴阳，万事万物离不开阴阳。这个根本就是阴阳。知其一，万事毕。

93. 凝神定气，物我两忘，这是养生的真谛。

94. 主明则下安，以此养生则寿，殁世不殆，以为天下则大昌。

主不明则十二官危，使道闭塞而不通，形乃大伤，以此养生则殃，以为天下者，其宗大危，戒之戒之！

95. 五行相生相克的应用：

凡是因五脏太过引起的疾病，都可以用五行相克的方法对治。同样，凡是因为五行不足引起的疾病都可以用五行相生的方法解决。这是运用五行的根本原则。

96. 人们对于物质的欲望是无止境的。一旦这种欲望得不到控制，那等待我们的就是无止境的痛苦。

其实，物质能带来的享受，精神也能；药物能治疗疾病，心理疗法也能做到。所以，我们用一生来追求财富，不如用一生来培养出一种好的心态，让我们的精神达到一种超凡的境界。

97. 常打太极拳，益寿又延年。

98. 房宽地宽，不如心宽。

99. 记住，我们偶尔拉肚子、打喷嚏、咳嗽、发烧等都是我们自己的身体修复系统在工作，不要一出现这些症状就滥用药物。

100. 很多重病或绝症，都只有一个理由：恨。

当这恨没了，病也必会一起消失。这世间最难解的是绵延不止的恨，固有解不开的恨，才有治不好的病。

**Comment by zhouyuchong** [comment]
21:00~3:00的睡眠时间。。。。。？

**Comment by wyrover** [comment]
> 21:00~3:00 的睡眠时间。。。。。？

这个指这个时间段必须睡了，也就是根据子午流注来安排时间睡觉，养肝胆。超过 3:00 是肺经，也得睡。

**Comment by ldgeng** [comment]
某些确实没有科学依据
