### ISSUE TITLE
怎么能抽烟还长寿

### ISSUE THREAD

**Issue by Carpe-Wang** [geekan/HowToLiveLonger#47]
有什么办法吗？

**Comment by MaitreChen** [comment]
不过肺😂

**Comment by augusttty** [comment]
喝茶。本人去过潮汕那边，每家必备一套茶具，那边人抽烟超猛，基本上不带断的。但是人家喝茶也是从早喝到晚，那边人很长寿。有一天晚上我跟朋友，远远的看到村子里灯下冒浓烟，还以为是在烧烤，结果走近一看几个大爷在抽烟。。
当然，最好还是不要抽，要抽的话试试电子烟？

**Comment by reezhu** [comment]
潮汕食道癌概率是其他地区的好几倍

> 喝茶。本人去过潮汕那边，每家必备一套茶具，那边人抽烟超猛，基本上不带断的。但是人家喝茶也是从早喝到晚，那边人很长寿。有一天晚上我跟朋友，远远的看到村子里灯下冒浓烟，还以为是在烧烤，结果走近一看几个大爷在抽烟。。 当然，最好还是不要抽，要抽的话试试电子烟？

**Comment by fanefanes** [comment]
抽假烟

**Comment by CTCSU** [comment]
> 潮汕食道癌概率是其他地区的好几倍
> 
> > 喝茶。本人去过潮汕那边，每家必备一套茶具，那边人抽烟超猛，基本上不带断的。但是人家喝茶也是从早喝到晚，那边人很长寿。有一天晚上我跟朋友，远远的看到村子里灯下冒浓烟，还以为是在烧烤，结果走近一看几个大爷在抽烟。。 当然，最好还是不要抽，要抽的话试试电子烟？

之前看到的资料是说以前喝茶温度都比较高，高温是引发食道癌的关键因素。
