### ISSUE TITLE
What about english translation ?

### ISSUE THREAD

**Issue by phadtrapong** [geekan/HowToLiveLonger#51]
Hi guys, What about any english translation ? This looks like a very useful repo.

**Comment by geekan** [comment]
sure. contribution needed.

**Comment by charmitro** [comment]
Would love to translate from English to Greek after this.

**Comment by 53jk1** [comment]
Also from English to Polish after this. :)

**Comment by Explosion-Scratch** [comment]
Would love an english translation!

**Comment by AlexandreBiguet** [comment]
I could help with the English to French translation after that :)  (if that makes sense for people)
