### ISSUE TITLE
考虑开启discussion功能

### ISSUE THREAD

**Issue by yihozhang** [geekan/HowToLiveLonger#52]
现在的issues区同时包含了报告问题/改进和评价两种功能，导致issue区的噪音比较高（ 如 #28 , #31 , #33 , #39 , #40 等 )    。建议开启GitHub的discussion功能，可以对一部分与改进本项目无关的issue进行分流。

参考：https://docs.github.com/en/discussions

**Comment by geekan** [comment]
听起来不错。有哪个开源工程用这个功能用的比较好的，我看看一般怎么维护

**Comment by yihozhang** [comment]
我也不是很确定哪个社区用的比较好，以下是我顺手找到的几个：

https://github.com/Kindelia/Kind/discussions
https://github.com/ballerina-platform/ballerina-lang/discussions
https://github.com/egraphs-good/egg/discussions

**Comment by FarmerChillax** [comment]
感觉可以直接使用 GitHub 的 Discussions

**Comment by geekan** [comment]
已开启
