### ISSUE TITLE
吃辣和痔疮怎么才能共存？

### ISSUE THREAD

**Issue by Ak47biubiuaa** [geekan/HowToLiveLonger#55]

**Comment by geeklys** [comment]
根据我的经验：

- 不要在连续两个消化周期内吃辣，菊花感到不适应立刻停止吃辣。
- 便便后把菊花清洗干净！有条件用水清洗最好，湿厕纸是神器！减少对菊花刺激。

PS: 吃辣不是罹患痔疮的原因，只是痔疮发作时加剧不适的诱因。

**Comment by xiaomingjava** [comment]
好了再吃

**Comment by dysodeng** [comment]
做为一个割过痔疮的过来人的经验：吃辣不太会得痔疮，诱发痔疮比较大的因素是久坐久站。平时多运动，不要一直坐着不活动。
PS:我做完痔疮手术后，1年内没吃辣，后面吃辣也没有啥了，7、8年来到现在一直都没再犯过

**Comment by zhoufupeng** [comment]
开塞露。
