### ISSUE TITLE
论辣椒炒鸡蛋的ACM

### ISSUE THREAD

**Issue by yonghui666** [geekan/HowToLiveLonger#57]
因：吃辣ACM-67%；吃鸡蛋 ACM+7%；
国：辣椒炒鸡蛋，依然是增加寿命？？？

**Comment by deerLoves** [comment]
需要看你投入的辣椒鸡蛋比，建议多放辣椒少放鸡蛋

**Comment by milk2we** [comment]
|
Shengyu Fan
shandong normal university - 
Master
***@***.***
Jinan,Shandong, China
|
在2022年4月22日 ***@***.***> 写道：

因：吃辣ACM-67%；吃鸡蛋 ACM+7%；
国：辣椒炒鸡蛋，依然是增加寿命？？？

**Comment by milk2we** [comment]
这就通知食堂增加这个菜谱

**Comment by geekan** [comment]
鸡蛋主要还是蛋黄。蛋白是-ACM的

**Comment by milk2we** [comment]
是因为蛋黄的胆固醇含量吗？
