### ISSUE TITLE
电子烟可以讨论下吗

### ISSUE THREAD

**Issue by augusttty** [geekan/HowToLiveLonger#58]
RT

**Comment by nextprops** [comment]
烟龄十几年，说下实际情况。
使用电子烟一年后，目前已经戒烟了。
我不知道电子烟的成分是否比香烟更加危害健康，但是在使用过程中电子烟确实不会产生难闻的二手烟味道。而且不会清嗓子（抽香烟的人都会有痰）。目前看来结果还可以。

**Comment by UniverseInHeart** [comment]
能不抽尽量还是不抽

**Comment by geekan** [comment]
这类实验跨度一般都是十几年到几十年，电子烟目前没有足够长的数据。但是从已有的研究来看，核心还是看吸入的物质
https://news.sina.com.cn/s/2021-12-13/doc-ikyamrmy8593541.shtml
