### ISSUE TITLE
听说研究过根治鼻炎，能分享下吗？@geekan 

### ISSUE THREAD

**Issue by hong4cong** [geekan/HowToLiveLonger#63]
@geekan

**Comment by YR1044** [comment]
慢性鼻炎，鼻窦炎患者同问

**Comment by bianliuzhu** [comment]
同问

**Comment by typistZxd** [comment]
过敏性鼻炎呢？

**Comment by zhangliuyang1** [comment]
过敏性鼻炎同问

**Comment by alonranger** [comment]
> 过敏性鼻炎呢？

过敏性的治不了，只能缓解

**Comment by geekan** [comment]
2020欧洲鼻窦炎和鼻息肉意见书 - 慢性鼻-鼻窦炎的应对方法与证据
![慢性鼻-鼻窦炎治疗依据和建议](https://user-images.githubusercontent.com/2707039/164888875-c48eaae9-17da-4b15-921b-4112c602b0ea.jpeg)

**Comment by geekan** [comment]
原文：https://www.rhinologyjournal.com/Documents/Supplements/EPOS2020translation-Chinese-full_text.pdf
@hong4cong @YR1044 @bianliuzhu

**Comment by geekan** [comment]
高证据等级意味着有比较高的依据、大量的实验。目前公认比较可靠的就是：
- 不伴鼻息肉时：长期服用小剂量大环内酯（一般选用克拉霉素），伴鼻息肉时一般认为效果较差（但实验文献并不多）
- 鼻腔冲洗 / 等渗盐水洗鼻（高渗高温一般认为没有实际作用）
- 局部糖皮质激素

**Comment by luchaoshuai** [comment]
关在上海，天天晚上后半夜都被“鼻子”难受醒，太辛苦了。

**Comment by SQDzhuzhuxia** [comment]
有没有根治的朋友，我女朋友就是鼻窦炎，很麻烦一直没治好
