### ISSUE TITLE
能不能考虑一下开一个discussion，讨论下怎么活下去？

### ISSUE THREAD

**Issue by P0etry-rain** [geekan/HowToLiveLonger#68]
同标题

**Comment by SONGMENGSEN** [comment]
1. 我快活不下去了，钱少事多，没有希望。同楼上

**Comment by j0rGeT** [comment]
躺平

**Comment by LiYuxuanhaha** [comment]
考虑移民嘛，至少可以让自己的子代过得没有这么悲惨

**Comment by azusachino** [comment]
这种还是找专业的心理咨询师吧，很多大环境之类的事情是个人没办法去改变的，但是个人想法是可以变的。
简单来说：有吃的有住的就能活下去；对你来说，现在最大的阻碍又是什么呢？

**Comment by dysodeng** [comment]
大环境如此，都不过好啊

**Comment by JoenZhu** [comment]
上海这波疫情，看看底层有多么的绝望

**Comment by BackMountainDevil** [comment]
建议各位都去看医生啊，看开一点。我还有几台手术都不慌

**Comment by P0etry-rain** [comment]
> 考虑移民嘛，至少可以让自己的子代过得没有这么悲惨

不考虑 不想做个无根的浮萍

**Comment by j0rGeT** [comment]
食品安全也好差啊，医院很多年轻人就肠胃不好的

**Comment by Myfanqie** [comment]
建议上班摸鱼

**Comment by jonny77** [comment]
> 建议各位都去看医生啊，看开一点。我还有几台手术都不慌

是你给别人做手术 还是你被别人做手术?

**Comment by PigeonAOA** [comment]
建议utools加摸鱼阅读插件
