### ISSUE TITLE
是否有兴趣开一个 how to look young

### ISSUE THREAD

**Issue by KargathEx** [geekan/HowToLiveLonger#7]
看到这个repo我就想起来这个知乎问题

[长相显老的人如何变年轻？ - 陈诺的回答 - 知乎](https://www.zhihu.com/question/21700415/answer/38613501)

三十岁以前的人，改善生活方式，吃好睡好，适量运动，逆生长不是神话。三十岁以后基本靠钱保养——不是用来买保养品，什么抗皱美白，什么金线莲燕窝，效果一律可疑。钱是用来构筑安稳无忧的生活，减轻焦虑，保持心情愉快，维持低压生活的。开朗乐观的心态，投入有成就感的工作，安稳和乐的家庭，彼此关怀沟通的爱人朋友，能达到比钱更好的效果。但比起钱来说，这些困难多了。

你们精力这么丰富，是否有兴趣也开一个repo来整理此类问题呢？、

---

题外话：

我觉得你们有一点变态，总以为有了知识就能增加对生活的掌控感,连这种事都开一个项目。
且喜欢用数据来给自己增加说服力。
但是给出的这些数据都好随便...
而且我个人不太相信那些统计结果对每一个个体有什么重大意义.

借用一句[木遥老师](http://blog.farmostwood.net/863.html)的话：
>我们只有一辈子，大数定律对我们没意义。

**Comment by geekan** [comment]
其实是有的。看david sinclair，1969年出生的，现在53岁，但你看视频会觉得这个人就是30岁

**Comment by zzyyds** [comment]
反正不管30前后，保养一定是要的，起码清洁/水/乳/防晒一定要做好。

**Comment by KargathEx** [comment]
那个.. 我就是吐槽下，自己没有把github当作论坛的习惯，repo主感兴趣的话把这个专题也加进来呀。
我先关了，抱歉 =_=
