### ISSUE TITLE
喝茶ACM影响

### ISSUE THREAD

**Issue by robinjoe93** [geekan/HowToLiveLonger#72]
喝茶（-8%~15% ACM）

这个 15%是没有问题的吗？

**Comment by CTCSU** [comment]
有论文的，我之前在丁香园上看到过相关的文章，来源也是相关的研究。

**Comment by geekan** [comment]
符号问题。已知

**Comment by qytayh** [comment]
喝茶分红茶绿茶奶茶吗

**Comment by ziping46** [comment]
![image](https://user-images.githubusercontent.com/38586831/165013984-35c63bd5-c6f4-48fa-a10c-92c55ee29eba.png)

**Comment by ziping46** [comment]
> 喝茶分红茶绿茶奶茶吗

我查了一下文献，该文献是研究喝茶对血脂的影响，它是说发酵茶和非发酵茶里面的有效物质接近，花茶比较少。但作者强调这个实验样本下，不同饮茶种类与对血脂的影响是否存在差异,还有待进一步研究证实。
