### ISSUE TITLE
有没有失眠的，讨论下病情和治疗方案呗

### ISSUE THREAD

**Issue by dysodeng** [geekan/HowToLiveLonger#73]

**Comment by xieqiongjie** [comment]
我最近在吃中药丸调理身体，有效果0 0

**Comment by monkeyk** [comment]
我的经验是：强制睡眠法（不睁开眼睛一直强制下去，会睡着的，不管是闭上1小时还是2小时）

**Comment by abhipreetham** [comment]
尝试以 20-10 次间隔连续深呼吸

**Comment by DontSerious** [comment]
早上早起，一起身就拉开窗帘，让身体知道现在是早上，调整生物钟(个人玄学办法)

**Comment by dysodeng** [comment]
> 我最近在吃中药丸调理身体，有效果0 0

你是去找了中医去调理吗

**Comment by dysodeng** [comment]
> 我的经验是：强制睡眠法（不睁开眼睛一直强制下去，会睡着的，不管是闭上1小时还是2小时）

我试试，估计需要点意志力，哈哈哈

**Comment by cothee** [comment]
可以看中医。北京中医医院，推荐张捷专家团队

**Comment by ljchen1129** [comment]
怼了一段时间的褪黑素，现在好像药物依赖了，没啥效果了

**Comment by dysodeng** [comment]
> 怼了一段时间的褪黑素，现在好像药物依赖了，没啥效果了

我也是吃了一段时间褪黑素，但是长期这样也不是办法

**Comment by hanlihub** [comment]
失眠说是和体内的多巴胺、5-羟色胺（血清素）有关
