### ISSUE TITLE
出一个每天久座多久比较好？是否与寿命长短有关？

### ISSUE THREAD

**Issue by monkeyk** [geekan/HowToLiveLonger#74]
反正程序员座的时长都不短。

**Comment by Eminem-x** [comment]
看过一篇文章，大概意思就是说坐一个小时左右，起来活动 5 ~ 10 分钟，是非常有必要的。

**Comment by mayef** [comment]
久坐和看电视时间与全因死亡、心血管疾病、癌症和2型糖尿病发病高风险相关，是独立风险因素。久坐事件每天每增加1小时，心血管疾病发生风险增加4%，癌症增加1%，全因死亡风险增加4%。分层分析显示，在大多数静态活动人群中，高BMI、糖尿病和高血压高风险者进一步增加全因死亡率，而较高身体活动水平(10.1~19.9MET-h/w)降低全因死亡风险。
全因死亡和CVD死亡风险增加的久坐时间阈值是6~8h/d，看电视时间阈值是3~4h/d。
——《中国居民膳食指南科学研究报告（2021年）》

**Comment by mayef** [comment]
[世卫组织关于身体活动和久坐行为的指南](https://apps.who.int/iris/bitstream/handle/10665/337001/9789240014947-chi.pdf)

**Comment by geekan** [comment]
LGTM @mayef 可以提个PR

**Comment by Michael18811380328** [comment]
这个有理有据，引用权威，和程序员密切相关。
