### ISSUE TITLE
How to live forever

### ISSUE THREAD

**Issue by Jesse3692** [geekan/HowToLiveLonger#78]

**Comment by siduck** [comment]
Not possible physically but if you do great things then you might live forever in the hearts of people

**Comment by geekan** [comment]
https://www.thepaper.cn/newsDetail_forward_14414036

**Comment by NeilKleistGao** [comment]
人类是有极限的，除非……

**Comment by TingLen** [comment]
> 人类是有极限的，除非……

我不做人了！

**Comment by jiangzhuti** [comment]
+1s
