### ISSUE TITLE
how to live with a girlfriend

### ISSUE THREAD

**Issue by skyforrun** [geekan/HowToLiveLonger#86]
you known,A girl friend can make we happy,have fun everyday

**Comment by HaSai666** [comment]
hahaha, I also want to know!

**Comment by BodyCSoulN** [comment]
working hard to earning more money.

**Comment by qhy040404** [comment]
lol:joy:

**Comment by ruiq** [comment]
> A girl friend can make we happy 

???

**Comment by PigeonAOA** [comment]
lol

**Comment by hashtafak** [comment]
https://www.quora.com/Why-do-so-many-programmers-not-have-girlfriends

**Comment by fantasua** [comment]
lol
