### ISSUE TITLE
如何用出生日期和星座算未来女朋友QQ号

### ISSUE THREAD

**Issue by xiaojiangGangGang** [geekan/HowToLiveLonger#87]
我2003.7.15 巨蟹座 怎么能算出我未来女朋友QQ号

**Comment by tzhichao** [comment]
> 

多吃点六个核桃补补脑子，小孩

**Comment by fzyjiangfeng** [comment]
你写个随机生成10位数的方法生成啊

**Comment by xiaojiangGangGang** [comment]
> 你写个生成经常10个直接的方法啊

qq没有10位的 能帮我算算5位 富婆女朋友吗

**Comment by xiaojiangGangGang** [comment]
> > 
> 
> 多吃点六个核桃补补脑子，小孩

天天喝QQ星 !

**Comment by slanceli** [comment]
我02年5月金牛座

**Comment by xuerzong** [comment]
我觉得下面的方法能够解决楼主的问题
```typescript
function findGirlFriendQQByDOBAndConstellation(dob: string, constellation: string) {
    throw new Error('404 not found')
}
```

**Comment by wn0112** [comment]
1. 打开陌陌
2. 编辑并发动态：我朋友想喝茶
即可找到女朋友QQ

**Comment by Quandong-Zhang** [comment]
我觉得这个应该能解决你的需求
`class GirlFriendNotFoundError(Exception):
    pass

def FindGirlFriendQQIdByBirthday(birthday):
    try:
        getGirlFriend(birthday)
    except:
        raise GirlFriendNotFoundError("别做梦了")

if __name__=="__main__":
    FindGirlFriendQQIdByBirthday(input("Please input your birthday:"))`

**Comment by Quandong-Zhang** [comment]
我觉得这个应该能解决你的需求
```python
class GirlFriendNotFoundError(Exception):
    pass

def FindGirlFriendQQIdByBirthday(birthday):
    try:
        getGirlFriend(birthday)
    except:
        raise GirlFriendNotFoundError("别做梦了")

if __name__=="__main__":
    FindGirlFriendQQIdByBirthday(input("Please input your birthday:"))
```

**Comment by zzrs123** [comment]
你已经快成年了，你要学会自己`new`一个

**Comment by ldgeng** [comment]
玄学是吧
