### ISSUE TITLE
就吃鸡蛋！就吃鸡蛋！就吃鸡蛋！

### ISSUE THREAD

**Issue by VillagerTom** [geekan/HowToLiveLonger#91]
没有鸡蛋的水煮泡面是没有灵魂的。(doge)

**Comment by hanlihub** [comment]
鸡蛋黄少吃

**Comment by Kanayukii** [comment]
@hanlihub 关于蛋黄的问题正在这里讨论：
https://github.com/geekan/HowToLiveLonger/issues/90

**Comment by Myfanqie** [comment]
我不仅要吃，我还一次要吃好几个鸡蛋

**Comment by VillagerTom** [comment]
@Kanayukii 這位日本網友您好，我是來自中國大陸北方的網友。
