### ISSUE TITLE
白肉是啥肉？肥肉嘛？

### ISSUE THREAD

**Issue by nothking** [geekan/HowToLiveLonger#93]
不明白白肉是啥？？？
还有就是亚精胺是啥鬼？？？我咋感觉有点不太妙？？？

**Comment by Interstellar750** [comment]
狭义上是指家禽的肉
具体可以参考[维基百科](https://zh.m.wikipedia.org/wiki/白肉)

**Comment by geekan** [comment]
@Interstellar750 有兴趣的话可以贡献一下，把link挂到白肉上

**Comment by Interstellar750** [comment]
> @Interstellar750 有兴趣的话可以贡献一下，把link挂到白肉上

readme 里似乎已经有关于红肉白肉的差别与介绍了，再挂一个维基百科的链接似乎有点多余 😯

~~还有个原因就是本人文笔不太好~~

**Comment by LiWeiQiangAndroid** [comment]
白切鸡，哈哈

**Comment by 378406712** [comment]
鱼肉-  -

**Comment by sincerefly** [comment]
鸡肉、鱼肉？

**Comment by 996fuckyou** [comment]
鱼虾这种处于食物链底层的肉

**Comment by cv0cv0** [comment]
肥肉叫脂肪，那不叫肉；白肉是指白色的肉，比如禽肉、鱼虾蟹肉。

**Comment by Damonxy** [comment]
就是肥肉，肥肉吃起来又香又健康。我吃饭没肥肉都不香。。。。

**Comment by deepdarkfans** [comment]
> 肥肉叫脂肪，那不叫肉；白肉是指白色的肉，比如禽肉、鱼虾蟹肉。

有些地方肥肉叫白肉，瘦肉叫红肉

**Comment by ldgeng** [comment]
你可以出门左转百度百科
