### ISSUE TITLE
【心脏骤停】建议找个有AED的办公楼上班，并且给大家普及CRP相关的知识

### ISSUE THREAD

**Issue by Degfy** [geekan/HowToLiveLonger#95]
[平均每天死亡1500人！心脏骤停，离我们有多远？](https://www.163.com/dy/article/GDU1197N0519B9KP.html)

**Comment by fanwenlie** [comment]
来我们公司吧，配有AED，并且离北医三院近，猝死概率大大减少😂

**Comment by Degfy** [comment]
> 来我们公司吧，配有AED，并且离北医三院近，猝死概率大大减少😂

我们公司也买了AED了！

**Comment by rahjuu** [comment]
应该是 CPR 吧
