### ISSUE TITLE
[修正]每天喝可乐能降低死亡率

### ISSUE THREAD

**Issue by wn0112** [geekan/HowToLiveLonger#98]
根据本文档描述：
* 每天一杯可乐增加全因死亡率 7%
* 每天一杯咖啡降低死亡率 10%~13%，因为咖啡因
* 可乐含有咖啡因

综上，每天喝可乐降低死亡率 3% ~ 6%。
## `大家可乐喝起来！！`

**Comment by Yanranh** [comment]
逻辑鬼才

**Comment by JaeNew** [comment]
只要想喝，有一万个理由[doge]

**Comment by prophesier** [comment]
根据本文档描述：

每天一杯可乐增加全因死亡率 7%
每天一杯咖啡降低死亡率 10%~13%，因为咖啡因
可乐含有咖啡因
综上，每天喝不含咖啡因的可乐增加死亡率 17% ~ 20%。

**Comment by MsHeavyFour** [comment]
逻辑天才

**Comment by zhonglang1906** [comment]
需要添加咖啡因的无糖可乐

**Comment by ldgeng** [comment]
强烈支持
